name: DuckGuilds
version: ${project.version}
main: at.theduggy.duckguilds.Main

commands:
  guild:
    description: The base guild-command
    guild.help:
      description: Get help to all guild-commands!